### ISSUE TITLE
LLVM fyi

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaIntervals/SetRounding.jl#5]
Apparently, IEEE Rounding for arithmetic ops is available with a deft llvm touch ("experimental" yet its in their v8 dev docs): [Constrained Floating Point Intrinsics](http://releases.llvm.org/6.0.1/docs/LangRef.html#id1768).

**Comment by dpsanders** [comment]
I guess we'll need to wait for llvm 8 to be incorporated in Julia, then...

**Comment by JeffreySarnoff** [comment]
Its in llvm 6

**Comment by JeffreySarnoff** [comment]
see https://github.com/maleadt/LLVM.jl/pull/111

**Comment by JeffreySarnoff** [comment]
closed via work in 2018
